### ISSUE TITLE
Data entry displaying as 1 day prior to data entered

### ISSUE THREAD

**Issue by ccrowley96** [ccrowley96/Qshare#1]
**Front end input**: February 16 --> **Data Stored** February 15
@EBogdanov2 this is a great first issue if you have any time over the next couple days!

## Important Info 
- Using redux-form
- Using react-datepicker
- Using moment.js (date-time library)
- inputValueFormat="YYYY/MM/DD"

I think this is a timezone issue!  Not sure what's causing the exact problem though.

**Comment by elaineg** [comment]
:'( let's help cory

**Comment by ccrowley96** [comment]
Fixed

**Comment by ccrowley96** [comment]
Time zone issue still happening!  Date saved in database is 1 day prior to date selected in time picker.

**Comment by ccrowley96** [comment]
Mongodb / Moment.js is saving dates correctly in offline local database, but live database is still having dates saved 1 day prior issue.
