### ISSUE TITLE
Update landing page!

### ISSUE THREAD

**Issue by ccrowley96** [ccrowley96/Qshare#27]
• https://www.julian.com/learn/growth/landing-pages

**Comment by ganes1410** [comment]
@ccrowley96  what needs to be updated??

**Comment by ccrowley96** [comment]
@ganes1410 hey man!  Are you a Queen's student?  We're doing a full landing page re-work with a call to action / navbar / feature description etc.. Making it more attractive basically.

**Comment by ganes1410** [comment]
@ccrowley96  no, i am not  queens student. I can't do the full page. I can work on any particular part.
