### ISSUE TITLE
.env environment variables for production / development

### ISSUE THREAD

**Issue by ccrowley96** [ccrowley96/Qshare#5]
Set up prod config
Set up dev config

**Comment by zackharley** [comment]
Check out https://www.npmjs.com/package/dotenv

This could be a good one for @EBogdanov2 to work on!

**Comment by ccrowley96** [comment]
@zackharley Just implemented!  Look over the config if you have time and see if it look ok :)

**Comment by ccrowley96** [comment]
Environment variables working!
