### ISSUE TITLE
Force https:// redirect

### ISSUE THREAD

**Issue by ccrowley96** [ccrowley96/Qshare#6]
Currently, both http://qshare.ca & https://qshare.ca are accessible

**Comment by zackharley** [comment]
Where are you hosting?

**Comment by ccrowley96** [comment]
@zackharley gcloud app engine!

**Comment by zackharley** [comment]
It should auto-upgrade to `https`

**Comment by ccrowley96** [comment]
What should be auto-upgraded?

**Comment by zackharley** [comment]
All requests should be upgraded from `http` -> `https` automatically when using GAE.

**Comment by ccrowley96** [comment]
Hmm both are accessible rn.  Checkout http://qshare.ca & https://qshare.ca

**Comment by ccrowley96** [comment]
This block worked!

```
// HTTPS Redirect for production
if (process.env.FORCE_SSL) {
    app.enable('trust proxy');
    app.use((req, res, next) => {
        if (req.secure) {
            next();
        } else {
            res.redirect('https://' + req.headers.host + req.url);
        }
    });
}
```
