### ISSUE TITLE
Use Google Maps for ride location

### ISSUE THREAD

**Issue by zackharley** [ccrowley96/Qshare#9]
You can query Google Maps for destination and pickup locations in your ride form. This would make it a lot easier to search against.

*With Google Maps:*
```
65 Front St W, Toronto, ON M5J 1E6
```

*Without Google Maps:*
```
Union Station, Toronto
65 Front Street Toronto
Union Train Station, Toronto, Ontario Canada
```

**Comment by ccrowley96** [comment]
https://github.com/ubilabs/react-geosuggest
